export const APP_SETTINGS = {
  debugBackgroundPanel: false,
  seasonClockStrategy: "season-time-first",
  weatherClockStrategy: "weather-first",
  calendarStrategy: "season-time-first",
  forecastHoursAhead: 36,
  forecastBackgroundOpacity: 0.8,
  calendarPageBackgroundOpacity: 0.12,
  calendarTileImageOpacity: 0.8,
  calendarTileOverlayOpacity: 0.3,
  calendarPrintTileImageOpacity: 0.62,
  calendarPrintTileOverlayOpacity: 0.26,
  calendarPrintTileMinHeightPx: 86,
  calendarPrintOrientation: "auto" as "auto" | "portrait" | "landscape",
} as const;
